name: Github Action Upload Zip to S3 on Push
run-name: ${{ github.actor }} triggered the workflow
on: [push]
jobs:
    create-zip:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Zip Repository
              run: zip -r latest-bundle.zip . -x "*.git*"

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_S3_BUCKET_REGION }}

            - name: Upload to S3
              run: aws s3 cp latest-bundle.zip s3://${{ secrets.AWS_S3_BUCKET }}/repo-${{ github.sha }}/latest-bundle.zip



