name: Github Action Upload Zip to S3 on Push
run-name: ${{ github.actor }} triggered the workflow
on: [push]
jobs:
    create-zip:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Zip Repository
              run: zip -r latest-bundle.zip . -x "*.git*"

            - name: Configure AWS Credentials
              run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} && export AWS_REGION=${{ secrets.AWS_S3_BUCKET_REGION }}

            - name: Set AWS Role
              run: aws sts assume-role --role-arn "arn:aws:iam::732930084772:role/PCSKDeveloperRole" --role-session-name UploadSession

            - name: Upload to S3
              run: aws s3 cp latest-bundle.zip s3://${{ secrets.AWS_S3_BUCKET }}/${{ secrets.AWS_S3_BUCKET_FOLDER }}/repo-${{ github.sha }}/latest-bundle.zip


